### ISSUE TITLE
Can't load questions because of missing csv file

### ISSUE THREAD

**Issue by jeancarlosg93** [umchooh/quiz-application#1]
app config csv file path is pointing to my c drive and looking for questions.csv but i don't have the file, so the program is failing to load it.

`<add key="QuestionsPath" value="C:\doc\csv files\questions.csv" />`

**Comment by umchooh** [comment]
Yes, the file located under bin/debug. As for now need to do manually cause in reality it should be on separate Data folder or a Database connection.     On Wednesday, April 24, 2024 at 02:49:53 p.m. EDT, Jean Carlos Guzman ***@***.***> wrote:  
 
 


app config csv file path is pointing to my c drive and looking for questions.csv but i don't have the file, so the program is failing to load it.

<add key="QuestionsPath" value="C:\doc\csv files\questions.csv" />
